# Generated by Django 3.2.14 on 2023-03-24 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_chainlevel_teamfive_teamfour_teamone_teamseven_teamsix_teamthree_teamtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.userdetails')),
            ],
        ),
    ]
