# Generated by Django 3.2.14 on 2023-03-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_withdrawals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='User_Image',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
