# Generated by Django 3.2.14 on 2023-03-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20230325_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebirth',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='rebirth',
            name='User_Key',
        ),
        migrations.RemoveField(
            model_name='teamfive',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamfive',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamfour',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamfour',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamseven',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamseven',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamsix',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamsix',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamthree',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamthree',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamtwo',
            name='Sponser',
        ),
        migrations.RemoveField(
            model_name='teamtwo',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userkey',
            name='UserId',
        ),
        migrations.DeleteModel(
            name='ChainLevel',
        ),
        migrations.DeleteModel(
            name='ReBirth',
        ),
        migrations.DeleteModel(
            name='TeamFive',
        ),
        migrations.DeleteModel(
            name='TeamFour',
        ),
        migrations.DeleteModel(
            name='TeamSeven',
        ),
        migrations.DeleteModel(
            name='TeamSix',
        ),
        migrations.DeleteModel(
            name='TeamThree',
        ),
        migrations.DeleteModel(
            name='TeamTwo',
        ),
        migrations.DeleteModel(
            name='UserKey',
        ),
    ]
