# Generated by Django 3.2.14 on 2023-03-26 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Key', models.CharField(max_length=255)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hierachi_Level', models.IntegerField()),
                ('Sponser_income', models.FloatField(null=True)),
                ('Level_income', models.FloatField(null=True)),
                ('My_income', models.FloatField(null=True)),
                ('ReBirth_Income', models.FloatField(null=True)),
                ('RebirthCount', models.IntegerField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('User_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rebirth.userkey')),
            ],
        ),
        migrations.CreateModel(
            name='TeamOne2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sponser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rebirth.userdetails2')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rebirth.userdetails2')),
            ],
        ),
    ]
